### ISSUE TITLE
Mark the JAX-RS dependency as `provided`

### ISSUE THREAD

**Issue by jpkrohling** [opentracing-contrib/java-jdbc#1]
The JAX-RS dependency should be marked as `provided`, as the party consuming the OT instrumentation has a concrete implementation as dependency already.

This is what's shown as `mvn dependency:tree` for a Wildfly Swarm application when requiring `io.opentracing.contrib:opentracing-jaxrs2:0.0.8`:
```
[INFO] +- io.opentracing.contrib:opentracing-jaxrs2:jar:0.0.8:compile
[INFO] |  +- io.opentracing.contrib:opentracing-concurrent:jar:0.0.1:compile
[INFO] |  \- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
```

**Comment by malafeev** [comment]
@jpkrohling I think you submitted issue against wrong project.
`java-jdbc` doesn't have any dependency on `jax-rs`

**Comment by jpkrohling** [comment]
Right, sorry :) The issue I have on this repo is another one (#2) .
