### ISSUE TITLE
URLParser reports "error occurs when paring jdbc url" for ldap Oracle url

### ISSUE THREAD

**Issue by farukciber** [opentracing-contrib/java-jdbc#104]
The URLParser is writing WARN level message 'error occurs when paring jdbc url' when 
using the JDBC connection url such as jdbc:oracle:thin:@ldap://oid:5000/mydb1,cn=OracleContext,dc=myco,dc=com 

This is a valid syntax for an Oracle JDBC connection url (see below)
https://docs.oracle.com/cd/E57185_01/EPMIS/apbs01s02.html

I can do a PR which is a regex change for EASY_CONNECT_PATTERN in OracleURLParser.

**Comment by malafeev** [comment]
@farukciber PR is welcome
