### ISSUE TITLE
New option to exclude spans faster than a latency threshold

### ISSUE THREAD

**Issue by naveedyahyazadeh** [opentracing-contrib/java-jdbc#109]
Similar to `slowQueryThresholdMs`, another beneficial optional setting would be a flag to omit spans that are faster than some latency threshold (i.e: `excludeSpansBelowQueryThreshold=100ms`). This can be implemented identically to the existing flag, but will reduce the number of spans produced by the Driver. 

This change will have significant performance benefits on systems that produce high numbers of JDBC spans. It will also keep spans whose latencies are small (fast requests) enough to be considered non-negligible. 

I think I have a solution in mind, and if you all are ok, I can spin up a PR!

**Comment by malafeev** [comment]
@naveedyahyazadeh PR is welcome

**Comment by naveedyahyazadeh** [comment]
Done, see PR #112 @malafeev

**Comment by naveedyahyazadeh** [comment]
Thank you for merging. Might I also bother you to release a new minor version release?

**Comment by malafeev** [comment]
@naveedyahyazadeh 0.2.14 is released

**Comment by naveedyahyazadeh** [comment]
Thank you for the swift responses and action!
