### ISSUE TITLE
Benchmarks - overhead of instrumented code without a tracer

### ISSUE THREAD

**Issue by jpkrohling** [opentracing-contrib/java-jdbc#15]
See opentracing/opentracing-java#295

Similar to the linked issue, this task is about measuring the overhead of traced JDBC calls when compared to their non-traced counter-parts.

Scenarios to test:

- [ ] Using an in-memory database, execute as many simple queries as possible (like `select 1`). Run it by time (X statements per minute) and by a fixed number of statements (task took N seconds to complete). Run twice, one with a traced JDBC driver and one without.

**Comment by malafeev** [comment]
@jpkrohling done

**Comment by jpkrohling** [comment]
Thanks!
