### ISSUE TITLE
tracing configuration question

### ISSUE THREAD

**Issue by redijedi** [opentracing-contrib/java-jdbc#3]
How can I limit the tracing such that it will only trace within an existing span?

**Comment by malafeev** [comment]
Do you mean that if there is no active span then don't trace jdbc call?

**Comment by redijedi** [comment]
Right. I'm only interested in JDBC calls within the context of larger requests. However, the way it is setup, it shows every call to the DB in isolation.

**Comment by tedsuo** [comment]
Seems pretty reasonable, I imagine there are other libraries that would want this as well.

**Comment by tedsuo** [comment]
Conversation happening in gitter on this btw https://gitter.im/opentracing/public

**Comment by malafeev** [comment]
done, introduced property `traceWithActiveSpanOnly=true`
