### ISSUE TITLE
H2 URL with implicit file mode does not work

### ISSUE THREAD

**Issue by Olard** [opentracing-contrib/java-jdbc#33]
H2 does not require that 'file:' is explicitly stated, but the H2URLParser does.

Example that worked with 0.0.8: jdbc:tracing:h2:~/db;AUTO_SERVER=TRUE;MODE=Oracle;MVCC=TRUE;LOCK_TIMEOUT=10000?traceWithActiveSpanOnly=true

**Comment by malafeev** [comment]
fixed by #34
