### ISSUE TITLE
peer.address in tag is not in common tags of opentracing 

### ISSUE THREAD

**Issue by changjiang2016** [opentracing-contrib/java-jdbc#47]
peer.address  is not common tags of opentracing.Why not use tags,such as peer.hostname and peer.port, instead of peer.address in the code ?

**Comment by malafeev** [comment]
because it's a trick to extract hostname/port when:
- database is in memory
- database is a file
- default port is different for different databases
would you like to submit a PR to fix all cases for major databases jdbc url variations?

**Comment by whiskeysierra** [comment]
> peer.address is not common tags of opentracing

It now is: https://github.com/opentracing/specification/pull/53
