### ISSUE TITLE
Control whether jdbc traces will be enabled or not.

### ISSUE THREAD

**Issue by osvaldopina** [opentracing-contrib/java-jdbc#56]
I'm new to this library and I could not find a way to turn it on and off depending on a global configuration. My need is to control wheter I'm going to trace jdbc calls or not and chage this behavior without the need to restart de application. Is it possible?

**Comment by malafeev** [comment]
In general it's not supported.
For interceptor usage `TracingDriver.setInterceptorProperty(true);` and `TracingDriver.setInterceptorProperty(false);` can work in some cases. But not always, it's limited to new connections and will not work for connection pool.
