### ISSUE TITLE
Using Oracle oci driver causes NPE, because of OracleURLParser "thin" expectations

### ISSUE THREAD

**Issue by ivan-slavchev** [opentracing-contrib/java-jdbc#71]
When using "oci" driver instead of "thin" the OracleURLParser is not capable of recognizing the pattern and returns null. This causes NPE later. At the same time the prefix that is expected for the OracleURLParser to pick up the connection string is "jdbc:oracle" and not "jdbc:oracle:thin". This makes it impossible to register custom parser specifically for oci.

**Comment by malafeev** [comment]
@ivan-slavchev would you like to submit PR?

**Comment by ivan-slavchev** [comment]
https://github.com/opentracing-contrib/java-jdbc/pull/72

**Comment by malafeev** [comment]
0.2.10 release with fix will be available in couple of hours
