### ISSUE TITLE
Error span when record doesn't exist in database.

### ISSUE THREAD

**Issue by Amiedeep** [opentracing-contrib/java-jdbc#74]
My database has a customer table with ID as a primary key. 

Expected behavior: When I search for a record that doesn't exist in the database, I should see an error span in the Jaeger UI. 

Actual behavior: When I search for a record that doesn't exist in the database, there is no error span created.

Code:

I'm calling JPA repository from a service using:
` Customer customer = customerRepository.findByid(customerID);`

findByid signature is like this:
`Customer findByid(long id);`

**Comment by malafeev** [comment]
error span will be created only if there is a mistake in query, failed connection etc.
but `findByID` returning null is valid case and normal span will be created.
