### ISSUE TITLE
Unable to find a driver that accepts 

### ISSUE THREAD

**Issue by zjutsuper** [opentracing-contrib/java-jdbc#9]
dataSource is DruidDataSource

 String realUrl = this.extractRealUrl(url);
            String dbType = this.extractDbType(realUrl);
            String dbUser = info.getProperty("user");
            Driver wrappedDriver = this.findDriver(realUrl);

this.findDriver(url) need using url not realUrl
this version will throw Excetpion
Caused by: java.sql.SQLException: Unable to find a driver that accepts jdbc:mysql://172.16.71.2:3306/tradecenter?useUnicode=true&characterEncoding=utf-8

**Comment by malafeev** [comment]
I will add it at least to README

**Comment by malafeev** [comment]
README updated
