### ISSUE TITLE
Support for other databases like db2, mssql, and others

### ISSUE THREAD

**Issue by oburgosm** [opentracing-contrib/java-jdbc#92]
Now, URLParser can extract data from:

* mysql
* oracle
* H2
* postgresql
* mariadb

It was useful extends it to support another databases like db2, mssql, and others.

I can do a PR for db2, as400 and mssql

**Comment by malafeev** [comment]
mssql is added by recent PR https://github.com/opentracing-contrib/java-jdbc/pull/89/files

others PRs are welcome

**Comment by oburgosm** [comment]
https://github.com/opentracing-contrib/java-jdbc/pull/93/files

**Comment by quaff** [comment]
Should this be closed now?
